// @vitest-environment jsdom
import { act, cleanup, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { PullToRefresh } from '../src/platform/components/PullToRefresh'
function touch(target: EventTarget, type: string, x: number, y: number) { const event = new Event(type, { bubbles: true, cancelable: true }); Object.defineProperty(event, 'touches', { value: type === 'touchend' ? [] : [{ clientX: x, clientY: y, pageY: y, screenY: y }] }); target.dispatchEvent(event) }
function Harness({ reload, disabled = false }: { reload: () => void; disabled?: boolean }) { return <><PullToRefresh disabled={disabled} onReload={reload} /><div className="pl-google-map" data-testid="map" /><form><div data-testid="form" /></form></> }
beforeEach(() => { Object.defineProperty(window, 'scrollY', { configurable: true, value: 0 }); Object.defineProperty(document, 'scrollingElement', { configurable: true, value: document.documentElement }) })
afterEach(() => { vi.useRealTimers(); cleanup() })
it('shows both iOS pull states then reloads the same page', () => { vi.useFakeTimers(); const reload = vi.fn(); render(<Harness reload={reload} />); act(() => touch(document.body, 'touchstart', 20, 0)); expect(screen.getByRole('status').textContent).toContain('引っ張って更新'); act(() => touch(document.body, 'touchmove', 20, 70)); expect(screen.getByRole('status').textContent).toContain('離して更新'); act(() => touch(document.body, 'touchend', 20, 70)); expect(screen.getByRole('status').textContent).toContain('更新中'); act(() => vi.advanceTimersByTime(180)); expect(reload).toHaveBeenCalledTimes(1) })
it('ignores short pulls, maps, forms, and non-top scroll positions', () => { vi.useFakeTimers(); const reload = vi.fn(); render(<Harness reload={reload} />); act(() => { touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 40); touch(document.body, 'touchend', 0, 40) }); for (const target of [screen.getByTestId('map'), screen.getByTestId('form')]) act(() => { touch(target, 'touchstart', 0, 0); touch(target, 'touchmove', 0, 100); touch(target, 'touchend', 0, 100) }); Object.defineProperty(window, 'scrollY', { configurable: true, value: 20 }); act(() => { touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 100); touch(document.body, 'touchend', 0, 100); vi.advanceTimersByTime(300) }); expect(reload).not.toHaveBeenCalled() })
it('does not run on protected screens or twice while refreshing', () => { vi.useFakeTimers(); const reload = vi.fn(); const view = render(<Harness reload={reload} disabled />); act(() => { touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 100); touch(document.body, 'touchend', 0, 100); vi.advanceTimersByTime(300) }); expect(reload).not.toHaveBeenCalled(); view.rerender(<Harness reload={reload} />); act(() => { touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 100); touch(document.body, 'touchend', 0, 100); touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 100); touch(document.body, 'touchend', 0, 100); vi.advanceTimersByTime(180) }); expect(reload).toHaveBeenCalledTimes(1) })
