// @vitest-environment jsdom
import { act, cleanup, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { PullToRefresh } from '../src/platform/components/PullToRefresh'
import { useRefreshTask } from '../src/platform/lib/pullToRefresh'
function touch(target: EventTarget, type: string, x: number, y: number) { const event = new Event(type, { bubbles: true, cancelable: true }); Object.defineProperty(event, 'touches', { value: type === 'touchend' ? [] : [{ clientX: x, clientY: y }] }); target.dispatchEvent(event) }
function Harness({ refresh, disabled = false }: { refresh: () => Promise<void>; disabled?: boolean }) { useRefreshTask(refresh); return <><PullToRefresh disabled={disabled} /><div className="pl-google-map" data-testid="map" /><form><div data-testid="form" /></form></> }
beforeEach(() => { Object.defineProperty(window, 'scrollY', { configurable: true, value: 0 }); Object.defineProperty(document, 'scrollingElement', { configurable: true, value: document.documentElement }) })
afterEach(cleanup)
it('captures an iOS-style document gesture and refreshes after 82px', async () => { const refresh = vi.fn().mockResolvedValue(undefined); render(<Harness refresh={refresh} />); act(() => { touch(document.body, 'touchstart', 20, 0); touch(document.body, 'touchmove', 20, 100) }); expect(screen.getByRole('status').textContent).toContain('離して更新'); act(() => touch(document.body, 'touchend', 20, 100)); await waitFor(() => expect(refresh).toHaveBeenCalledTimes(1)) })
it('ignores short pulls, maps, forms, and non-top scroll positions', () => { const refresh = vi.fn().mockResolvedValue(undefined); render(<Harness refresh={refresh} />); act(() => { touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 50); touch(document.body, 'touchend', 0, 50) }); for (const target of [screen.getByTestId('map'), screen.getByTestId('form')]) act(() => { touch(target, 'touchstart', 0, 0); touch(target, 'touchmove', 0, 100); touch(target, 'touchend', 0, 100) }); Object.defineProperty(window, 'scrollY', { configurable: true, value: 20 }); act(() => { touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 100); touch(document.body, 'touchend', 0, 100) }); expect(refresh).not.toHaveBeenCalled() })
it('does not run on protected screens or twice while refreshing', async () => { let release = () => {}; const refresh = vi.fn(() => new Promise<void>((resolve) => { release = resolve })); const view = render(<Harness refresh={refresh} disabled />); act(() => { touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 100); touch(document.body, 'touchend', 0, 100) }); expect(refresh).not.toHaveBeenCalled(); view.rerender(<Harness refresh={refresh} />); act(() => { touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 100); touch(document.body, 'touchend', 0, 100); touch(document.body, 'touchstart', 0, 0); touch(document.body, 'touchmove', 0, 100); touch(document.body, 'touchend', 0, 100) }); expect(refresh).toHaveBeenCalledTimes(1); release() })
