/** Columns safe for the browser Supabase client. Never include stripe_account_id. */
export const PERFORMER_CLIENT_SELECT = [
  'id',
  'stage_name',
  'bio',
  'genre',
  'country',
  'city',
  'photo_url',
  'support_blurb',
  'stripe_onboarding_complete',
  'is_approved',
  'is_live',
  'live_started_at',
  'live_title',
  'stream_url',
  'share_location',
  'lat',
  'lng',
  'location_updated_at',
  'video_url',
  'awards',
  'appearances',
  'sns_json',
  'created_at',
  'updated_at',
].join(',')
